# -*- coding: utf-8 -*-
"""ETL y Clusterización de Empresas del S&P 500.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqNkv7qwKwWm_AiIiNj1WdyW9KjSC8IJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Cargar datos y limpiarlos
df = pd.read_csv('/Precios-empresas-CSV.csv')
print(df.head())
df = df.dropna()
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by=['Ticker', 'Date'])
df['Return'] = df.groupby('Ticker')['Precio_cierre'].pct_change() * 100
df = df.fillna(0)
print(df.head())

# Paso 3: Cálculo de Retornos Porcentuales Diarios - Paso 4: indicadores de volatilidad
resultados = df.groupby('Ticker').agg(
    std_return=('Return', 'std'),
    range_return=('Return', lambda x: x.max() - x.min()),
    mean_abs_return=('Return', lambda x: x.abs().mean()))
print(resultados)

# Paso 5: Escalamiento de los Datos
scaler = StandardScaler()
resultados_scaled = scaler.fit_transform(resultados)
resultados_scaled_df = pd.DataFrame(resultados_scaled, index=resultados.index, columns=resultados.columns)
print(resultados_scaled_df.head())

# Paso 6: Clusterización - Determinar clusters
inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=0)
    kmeans.fit(resultados_scaled_df)
    inertia.append(kmeans.inertia_)
plt.plot(range(1, 11), inertia, marker='o')
plt.xlabel('Número de clusters')
plt.ylabel('Inercia')
plt.title('Método del codo')
plt.show()

# Aplicar KMeans
n_clusters = 4
kmeans = KMeans(n_clusters=n_clusters, n_init=10, random_state=0)
kmeans.fit(resultados_scaled_df)
resultados_scaled_df['Cluster'] = kmeans.labels_
print(resultados_scaled_df.head())

resultados['Cluster'] = kmeans.labels_
df_clusters = resultados[['Cluster']].reset_index()
print(df_clusters)

# Reducir dimensionalidad
pca = PCA(n_components=2)
pca_result = pca.fit_transform(resultados_scaled_df.drop(columns='Cluster'))
pca_df = pd.DataFrame(pca_result, columns=['PC1', 'PC2'])
pca_df['Cluster'] = resultados_scaled_df['Cluster'].values
print(pca_df.head())

# Visualizar resultados
print(pca_df['Cluster'].value_counts())
pca_df = pca_df.dropna(subset=['Cluster'])
print(pca_df.head())
plt.figure(figsize=(10, 7))
scatter_plot = sns.scatterplot(data=pca_df, x='PC1', y='PC2', hue='Cluster', palette='viridis', s=100)
handles, labels = scatter_plot.get_legend_handles_labels()
scatter_plot.legend(handles=handles, labels=labels, title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.title('Visualización de Clusters')
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.tight_layout()
plt.show()

print(pca_df.isnull().sum())

# Empresas por cluster
df_clusters = pd.DataFrame({
    'Ticker': ['A', 'AAL', 'AAP', 'AAPL', 'ABT'],
    'Cluster': [1, 1, 1, 0, 0]
})

empresas_cluster_0 = df_clusters[df_clusters['Cluster'] == 0]
empresas_cluster_1 = df_clusters[df_clusters['Cluster'] == 1]
empresas_cluster_2 = df_clusters[df_clusters['Cluster'] == 2]
empresas_cluster_3 = df_clusters[df_clusters['Cluster'] == 3]

print("Empresas en Cluster 0:")
print(empresas_cluster_0)

print("\nEmpresas en Cluster 1:")
print(empresas_cluster_1)

print("\nEmpresas en Cluster 2:")
print(empresas_cluster_2)

print("\nEmpresas en Cluster 3:")
print(empresas_cluster_3)

df_clusters = resultados[['Cluster']].reset_index()
print(df_clusters)
for cluster_id in range(n_clusters):
    print(f"\nEmpresas en Cluster {cluster_id}:")
    empresas_cluster = df_clusters[df_clusters['Cluster'] == cluster_id]
    print(empresas_cluster)

#Paso 9: Análisis e Interpretación
#1. Interpretar los resultados:o Analiza los clusters y describe las características de cada grupo. ¿Qué patrones observas en las empresas agrupadas? ¿Hay algún comportamiento común en las empresas dentro de un mismo cluster?
'''Teniendo en cuenta el metodo de codo, seleccione 4 clusters.
Los clusters son:
Observo que en el cluster 0, hay agrupadas 270 empresas, que tienen una variabilidad en el retorno mas baja, es decir son empresas mas estables, en lo referente al precio de sus acciones, podemos decir que son menos volatiles.
La desviación estandar de estas empresas es más baja, lo que significa que sus movimientos son menos riesgosos.
Los rangos de retornos diarios son bajos, lo que puede indicar que no hay cambios extremos en los retornos.

Para el Cluster 1, hay agrupadas 166 empresas, en este grupo los retornos diarios son mas amplios, es decir hay una mayor volatilidad, sus rendimientos varian más y los precios son más extremos.

Para el Cluster 2, hay agrupadas 51 empresas, en este punto del análisis se puede evidenciar que estas empresas son un punto intermedio entre las que estan en el Cluster 0 y 1. Tanto su volatilidad como retornos diarios son intermedios, puede decirse que el riesgo tambien lo es.

Para el cluster 3, se agruparon 2 empresas, debido a que estas no fueron identificadas en los grupos anteriores, no se pueden generalizar resultados, deberiamos analizarlas de manera individual.'''


#2. Conclusiones: o Escribe un breve resumen de las conclusiones obtenidas a partir del análisis y la clusterización. ¿Cómo podría este análisis ser útil para tomar decisiones financieras?
'''Considero que este análisis puede ser útil para tomar decisiones financieras, porque permite conocer el perfil de las empresas, poniendo a disposición de los usuarios diversas opciones de inversión o un portafolio mas amplio.
Adicionalmente permite caracterizar el riesgo de las empresas por grupo, brindando al usuario la posibilidad de decidir mejor entre el mayor riesgo, mejor oportunidad de rentabilidad o por el contrario mayor estabilidad. Esto no solo permite
caracterizar las empresas, sino que tambien permite caracterizar el grupo de usuarios según las acciones donde decidan invertir, puede decirse que los usuarios que seleccionan el Cluster 0, son mas conservadores, o los que seleccionen empresas del cluster 1 estan más dispuestos a asumir mayores riesgos.'''